version: '3'
services:
  db-exchange:
    build: .
    container_name: db-exchange
    image: postgres:latest
    ports:
      - "54433:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: maxi
      POSTGRES_DB: Exchange
    networks:
      - database1

  api-exchange:
    build:
      context: ../ExChangeService
      dockerfile: Dockerfile
    image: api-exchange:latest
    container_name: api-exchange
    ports:
      - "8080:8080"
    depends_on:
      - db-exchange
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-exchange:5432/Exchange
      SPRING_DATASOURCE_USERNAME: maxi
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - database1
      - backend

  db-cars:
    build: .
    container_name: db-cars
    image: postgres:latest
    ports:
      - "54434:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: maxi
      POSTGRES_DB: Cars
    networks:
      - database2

  api-cars:
    build: .
    image: api-cars:latest
    container_name: api-cars
    ports:
      - "8081:8081"
    depends_on:
      - db-cars
      - api-exchange
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-cars:5432/Cars
      SPRING_DATASOURCE_USERNAME: maxi
      SPRING_DATASOURCE_PASSWORD: 1234
      exchange.rate.url: http://api-exchange:8080/ExRate/getExRateFrom
    networks:
      - database2
      - backend



networks:
  database1:
  database2:
  backend:
